# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_username', models.CharField(max_length=200)),
                ('client_company', models.CharField(max_length=200)),
                ('client_address', models.TextField(max_length=500)),
                ('client_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('client_email', models.CharField(max_length=100)),
                ('client_password', models.CharField(max_length=200)),
                ('client_status', models.CharField(choices=[(b'1', b'New'), (b'2', b'Verified'), (b'3', b'Active'), (b'4', b'Unknown')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Client')),
            ],
            options={
                'verbose_name_plural': 'Client profiles',
            },
        ),
    ]
