# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_client_client_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcampaign',
            old_name='campaing_perimeter',
            new_name='campaign_perimeter',
        ),
        migrations.AddField(
            model_name='clientcampaign',
            name='impression_target',
            field=models.BigIntegerField(default=0),
        ),
    ]
