# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_clientcampaign_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcampaign',
            name='campaign_name',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
