# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_auto_20160421_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_username', models.CharField(max_length=200)),
                ('driver_company', models.CharField(max_length=200)),
                ('driver_address', models.TextField(max_length=500)),
                ('driver_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('driver_email', models.CharField(max_length=100)),
                ('driver_password', models.CharField(max_length=200)),
                ('driver_status', models.CharField(choices=[(b'1', b'New'), (b'2', b'Verified'), (b'3', b'Active'), (b'4', b'Unknown')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_campaign_status', models.CharField(choices=[(b'1', b'Registered'), (b'2', b'Active'), (b'3', b'Finished'), (b'4', b'Unknown')], default=1, max_length=1)),
                ('campaign_earnings', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ClientCampaign')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Driver')),
            ],
            options={
                'verbose_name_plural': 'driver profiles',
            },
        ),
    ]
