# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_driver_drivercampaign_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ClientCampaignDetail'),
        ),
    ]
