# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_auto_20160423_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivercampaign',
            old_name='campaign_details',
            new_name='campaign_detail',
        ),
    ]
