# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_auto_20160423_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCampaignDailyDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_driver_on_road', models.IntegerField(default=0.0)),
                ('daily_total_distance_km', models.FloatField(default=0.0)),
                ('daily_total_impressions', models.FloatField(default=0.0)),
                ('daily_total_cost', models.FloatField(default=0.0)),
                ('wrap_type', models.CharField(choices=[(b'1', b'Full'), (b'2', b'Partial'), (b'3', b'Panel'), (b'4', b'Unknown')], default=b'4', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ClientCampaign')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCampaignDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_on_road', models.IntegerField(default=0.0)),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('total_impressions', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('wrap_type', models.CharField(choices=[(b'1', b'Full'), (b'2', b'Partial'), (b'3', b'Panel'), (b'4', b'Unknown')], default=b'4', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ClientCampaign')),
            ],
        ),
        migrations.RenameField(
            model_name='clientcampaigndetail',
            old_name='monthly_cap',
            new_name='daily_cap',
        ),
        migrations.RemoveField(
            model_name='clientcampaigndetail',
            name='monthly_km_cap',
        ),
        migrations.AddField(
            model_name='clientcampaigndetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 30, 14, 25, 48, 837850, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcampaigndetail',
            name='daily_km_cap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientcampaigndetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 30, 14, 25, 51, 822908, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_uuid',
            field=models.CharField(default=datetime.datetime(2016, 4, 30, 14, 25, 54, 371137, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcampaigndashboard',
            name='campaign_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ClientCampaignDetail'),
        ),
        migrations.AddField(
            model_name='clientcampaigndailydashboard',
            name='campaign_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.ClientCampaignDetail'),
        ),
    ]
