# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 12:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_auto_20160430_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_password',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='driver_username',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='drivercampaign',
            old_name='driver_campaign_status',
            new_name='campaign_status',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_phone_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_uuid',
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[(b'1', b'Hatchback'), (b'2', b'Sedan'), (b'3', b'SUV'), (b'4', b'Unknown')], default=b'4', max_length=1),
        ),
    ]
