# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_auto_20160504_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcampaign',
            name='campaign_city',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='clientcampaigndetail',
            name='cars_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientcampaigndetail',
            name='cars_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[(b'1', b'New'), (b'2', b'Verified'), (b'3', b'Active'), (b'4', b'Wrapped'), (b'5', b'Unknown')], max_length=1),
        ),
    ]
