# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_auto_20160514_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDailyEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trip_earning', models.FloatField(default=0.0)),
                ('trip_count', models.IntegerField(default=0)),
                ('total_trip_distance', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.Driver')),
            ],
        ),
        migrations.AlterField(
            model_name='clientcampaign',
            name='campaign_status',
            field=models.CharField(choices=[(b'1', b'New'), (b'2', b'Processing'), (b'3', b'Active'), (b'4', b'Closed'), (b'5', b'Unknown')], default=b'1', max_length=1),
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='campaign_status',
            field=models.CharField(choices=[(b'1', b'Requested'), (b'2', b'Active'), (b'3', b'Finished'), (b'4', b'Unknown')], default=1, max_length=1),
        ),
    ]
