# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_auto_20160615_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercampaign',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
