# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0019_auto_20160615_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 23, 1, 40, 9, 158149)),
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 23, 1, 40, 9, 158109)),
        ),
    ]
