# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 20:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0020_auto_20160723_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_password',
        ),
        migrations.AddField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 7, 22, 20, 14, 46, 839385, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 23, 1, 44, 26, 65665)),
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 23, 1, 44, 26, 65640)),
        ),
    ]
