# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-24 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_auto_20160723_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 24, 21, 52, 11, 369320)),
        ),
        migrations.AlterField(
            model_name='drivercampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 7, 24, 21, 52, 11, 369291)),
        ),
        migrations.AlterUniqueTogether(
            name='clientcampaigndetail',
            unique_together=set([('campaign', 'wrap_type')]),
        ),
    ]
